### ISSUE TITLE
Log in sessions seem very short

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/multi-dreams#236]
Old issue on this for reference Edgeryders-Participio/realities#194

Looking at that issue and checking keycloak, we still seem to have the same settings that worked up until ~saturday. Really weird.

@aerugo Are other people than you having the issue? What's your browser and version? Do you select "remember me" when logging in (confirmed: yes)?

**Comment by aerugo** [comment]
I am using another computer now, will try during the day to see if I can reproduce.

**Comment by aerugo** [comment]
Okay, so I know what I mean now.

Actually, the Keycloak session is fine. However, Dreams keeps logging me out - I have to click "Login or Sign up" all the time. I can keep the browser open, wait for an hour, and then I have to click the button again. This is annoying, as it might actually take quite some time to work on a Dream, and when you try to save you get errors because you are actually no longer signed in. 

Is this related to how Dreams handles the session, rather than the session on Keycloak?

**Comment by Powersource** [comment]
Hm ok. Which browser and browser version are you using? Have you tried in different browsers? Do you think it started happening towards the end of last week or do you think it could have been around much earlier, we just didn't notice?

**Comment by aerugo** [comment]
Using Chrome, version 90. Also Chrome at my Blivande computer, probably
also v 90.

If you open Dreams, log in, edit a dream and keep the browser open for 2
hours - are you still logged in?

**Comment by Powersource** [comment]
Yes just now tried that and worked like expected.
* Go to dream page
* Edit field
* Wait around 2 hours
* Edit another field
* No error

**Comment by Powersource** [comment]
On firefox 87

**Comment by aerugo** [comment]
Okay, let’s leave this and see if anyone else complains.
