### ISSUE TITLE
Filtering dreams

### ISSUE THREAD

**Issue by Diemo-zz** [Edgeryders-Participio/multi-dreams#269]
You are currently able to set questions that a dream should answer - e.g. Does the dream contain music?   There is also a facility to show that question on the front page, and to filter down to the dreams which have answered that question in the affirmative.

![image](https://user-images.githubusercontent.com/1898086/120999377-55de2180-c789-11eb-9292-94265c14f1f3.png)

Here the dream "Tiny Worlds, Big Adventures" has the Communal Spaces tag, but when you select communal spaces, there is nothing shown.

LNT+ seems to be the only question which works, shows even when the dream is not set to be LNT+.
![image](https://user-images.githubusercontent.com/1898086/120999710-b40b0480-c789-11eb-9171-47d02f54ea16.png)

![image](https://user-images.githubusercontent.com/1898086/120999774-c9802e80-c789-11eb-9e82-e6b7b9229973.png)

**Comment by aerugo** [comment]
This function is actually not intended for filtering. It is intended to show another Dream info than "summary" for all Dreams on the index page, in order to quickly be able to - for example - see all dream answers to "How can people co-create with you?"

However, I am starting to think that people don't really use this and that we should get rid of it. What do you think @gustavlrsn, @Powersource and @skoteskote 

We did however just introduce a tagging feature that works for filtering dreams. Maybe try that out @Diemo-zz?

**Comment by skoteskote** [comment]
Yes let's scrap this feature. I think the "Find dreams who are looking for cocreators" is either it's own function, or covered by the new tags.

**Comment by DiarmaidEverycs** [comment]
This appears fixed for our usecase. YThe tagging feature works
