### ISSUE TITLE
Ordering Dreams

### ISSUE THREAD

**Issue by Diemo-zz** [Edgeryders-Participio/multi-dreams#278]
This is more of a request.

It is well known that there exists a "First on the ballot" effect when people are voting, where the first people who are on the list get more votes (all other things being equal) than the last people on the list. We don't want to give any dreamers a disadvantage, so would it be possible to have the list of dreams be randomised when you on every load the page? (Actually, what would be ideal is if this was a setting you could turn on and off, where when it was off it kept the current behavior of listing them by age).

KiezBurn is going ahead, and has a fair few dreams on the platform now :).

**Comment by aerugo** [comment]
Yup, this is on the list in #32 and #13 
When does your granting open? Perhaps we can aim to have this done by then.

**Comment by Diemo-zz** [comment]
Granting opens on the 24th, and only runs for a week.

**Comment by aerugo** [comment]
@Powersource - can we make this happen for Kiezburn before their granting opens? 
Since we now get dreams paginated, does that mean we cannot do the sorting clientside? 
If we need to do the sorting in the backend, how hard would it be to implement a random sort order call for dreams in this in the coming week? I'm thinking we can switch to random sort by default for now, and allow the user to switch to "sort by last updated". To fix the "first on the ballot" bias, random needs to be the default option.

Eventually, we should also allow setting the default sort order in collection settings, but that can wait.

**Comment by Powersource** [comment]
I'll get on this after fixing the tag bug.

Could hopefully get this done before granting opens but no guarantees. I'd likely just switch the ordering to random, we can add the option to switch between the different sorts later.

Yeah due to pagination we'll need to do this in the backend but I think we would have wanted to put it there either way.

Should it be random per user/day/pageview/etc? Or no strong opinions as long as we avoid the "first on the ballot" bias?

**Comment by Powersource** [comment]
Ok so this is the least hacky/simplest/most performant thing I could come up with:

Add a field to all dreams that's a random float between 0 and 1. Get another number between 0 and 1 that's relatively unique to the current user (something like `(userId % 100)/100`). Query by sorting by the dream's number, and doing [`$gte`](https://docs.mongodb.com/manual/reference/operator/query/#comparison) the user's number. Return if we have enough results. If we want more results, do the same query but use $lt instead of $gte and then append that to the existing results.

Will start on this on tuesday.

**Comment by Powersource** [comment]
This [blog post](https://betterprogramming.pub/extract-random-documents-in-mongodb-while-preserving-pagination-6100e5357c65) had an interesting idea, you can use [`$project`](https://docs.mongodb.com/manual/reference/operator/aggregation/project/) to add new fields, that we'd then sort on. Then it might be slightly slower in theory because I guess we might not be able to benefit from indexes, but we wouldn't need to add a new field and we'd be able to do the whole thing in 1 query instead of 2.

More docs https://docs.mongodb.com/manual/meta/aggregation-quick-reference/#expressions

**Comment by DiarmaidEverycs** [comment]
If you are not able to have random ordering, could you flip it so that the earliest created are first? At least that way it is the dreamers who were most motivated that will get the advantage.

I don't think performance shouldn't be a big issue. We currently only have ~60 dreams

**Comment by aerugo** [comment]
I don’t think sort by first created makes much sense. In my experience,
it’s not the dreams that get created first that are the most ambitious or
motivated - on the contrary the more ambitious dreams often come later as
it takes some time to develop the concept before you put it up.

As it is right now, if they are still motivated they can end up on top
again by simply making an edit to their dream. One way for you guys to sort
of “pseudo randomize” the order until the real randomization gets
implemented would be for the admin to “randomly” add a white space to the
description of a Dreams.

But anyway, randomization will happen, and hopefully in time for when your
granting opens this week - we have a strategy and start working on it today
if I’m not mistaken.

**Comment by DiarmaidEverycs** [comment]
Oh, that is a good thing to know about the Psuedo-randomisation.   Hopefully not needed but if it is we can do it.

> on the contrary the more ambitious dreams often come later as
it takes some time to develop the concept before you put it up

I agree with this in general, but because of the uncertainty involving whether the event, people were not unloading dreams.   So the dreams that did get uploaded (I think 5 or 6) were from motivated people, and I didn't want them to be punished for being the most motivated.

> But anyway, randomization will happen, and hopefully in time for when your
granting opens this week

That would be amazing. Thanks for the quick response time here :)

**Comment by Powersource** [comment]
Made it work, just needs a review and merge. Guessing it's in by tomorrow.

**Comment by Powersource** [comment]
Ran into a few different bugs but they seem to all be fixed now, and the shuffling is now in
