### ISSUE TITLE
"Oops, we lost some of our funding" (inflation features wanted?)

### ISSUE THREAD

**Issue by LudwikJaniuk** [Edgeryders-Participio/multi-dreams#69]
I see on the mutations in graphQL that the optimistic case of getting more funding is supported code-wise, but the similar case of needing to decrease the budget is simply supposed to be impossible. In reality, I think it can happen that an event loses part of its funding. There should be a way to express this in the system.

One proposed way could be that "editBudget" does allow lowering the budget. What happens is that if the event is then exceeding its budget, we are in "over budget mode", and well, no grants are possible until that issue is resolved. This can be done either by purging dreams, having users revoke some grants individually, or by devaluing the currency value of the grants. This last option is a bigger feature but seems to me reasonable that it should exist. This is because it retains all the information about how people have voted so far.

What do you think? I don't have access to miro but had this discussion with Gustav so I just wanted to document this thought here.

**Comment by LudwikJaniuk** [comment]
Ayy, #69, nice

**Comment by aerugo** [comment]
I agree this is a useful feature. In fact, this has actually happened. At the Borderland 2017, the Dream grant fund was miscalculated due to a currency exchange error, resulting in a budget that was 15% more than what we could actually spend. Our solution at the time was to plead to the community to lower their Dream budgets until we reached the mark. 

We should add this as a planned feature.

**Comment by aerugo** [comment]
Made reduntant by #196
