### ISSUE TITLE
Create organization feature

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#81]
A url that we can send to some users.
A user must be auth to view this page
Any auth user that opens this page can create a new Organization
(Since currently a user can only be created from an organization - we have a chicken and an egg situation) - We need to some how duplicate the current user (Disconnect that user and reconnect it with a new token)

I've started to design the `Create Orgaznization` page (Which would also be the `Edit organization` page)- 
Currently, it's used internally - but probably in the near future, we would want to give users the ability to create those organizations.

(Please ignore the color scheme as this is only a draft to understand the components)
You can edit it by following this
https://www.figma.com/file/N9O2mfYylNV2ZkWOuyME0R/Material-Baseline-Design-Kit-Community?node-id=4%3A0

<img width="590" alt="Screen Shot 2020-07-30 at 20 31 20" src="https://user-images.githubusercontent.com/1032526/88954879-ba943a00-d2a3-11ea-938a-8960841d93e2.png">

**Comment by aerugo** [comment]
Gal and I discussed this feature and agreed that since it's within reach, we should go for it. Getting a number of test orgs and events in the next few months will make it a lot more rewarding to work on Dreams, and it's a lot more likely to happen if we can point people to a link where they can create their own Dreams org.

**Comment by rootux** [comment]
Done
